# -*- coding: utf-8 -*-
"""Random Password Generator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d9wD9qz4qnqRNVYqiNXCat6MhqgOqIjg
"""

import random
pw_length= int(input("Enter the length of password: "))
s="abcdefghijklmnopqrstuvwxyz01234567890ABCDEFGHIJKLMNOPQRSTUVWXYZ!@#$%^&*()?"
pw= "".join(random.sample(s,pw_length))
print(pw)